server:
  port: 8082
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
