server:
  port: 8081
  servlet:
    context-path: /catalog

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce1
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
